# Generated by Django 3.1.7 on 2021-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='name')),
                ('todo', models.CharField(max_length=50, verbose_name='todo')),
            ],
        ),
    ]
